
# LTE EEM cause definition

LIBLTE_MME_EMM_CAUSE_IMSI_UNKNOWN_IN_HSS = b'\x02'
LIBLTE_MME_EMM_CAUSE_ILLEGAL_UE = b'\x03'
LIBLTE_MME_EMM_CAUSE_IMEI_NOT_ACCEPTED = b'\x05'
LIBLTE_MME_EMM_CAUSE_ILLEGAL_ME = b'\x06'
LIBLTE_MME_EMM_CAUSE_EPS_SERVICES_NOT_ALLOWED = b'\x07' #no EPS switch to 2G
LIBLTE_MME_EMM_CAUSE_EPS_SERVICES_AND_NON_EPS_SERVICES_NOT_ALLOWED = b'\x08' # 8 This EMM cause is sent to the UE when it is not allowed to operate either EPS or non-EPS services. DOS
LIBLTE_MME_EMM_CAUSE_UE_IDENTITY_CANNOT_BE_DERIVED_BY_THE_NETWORK = b'\x09' # This EMM cause is sent to the UE when the network cannot derive the UE’s identity from the GUTI/S-TMSI/P-TMSI and RAI 
#e.g. no matching identity/context in the network or failure to validate the UE’s identity due to integrity check failure of the received message.
LIBLTE_MME_EMM_CAUSE_IMPLICITLY_DETACHED = b'\x0A' # implicitly detach ( used to force reconnect phone 
LIBLTE_MME_EMM_CAUSE_PLMN_NOT_ALLOWED = b'\x0B'
LIBLTE_MME_EMM_CAUSE_TRACKING_AREA_NOT_ALLOWED = b'\x0C'
LIBLTE_MME_EMM_CAUSE_ROAMING_NOT_ALLOWED_IN_THIS_TRACKING_AREA = b'\x0D'
LIBLTE_MME_EMM_CAUSE_EPS_SERVICES_NOT_ALLOWED_IN_THIS_PLMN = b'\x0E'
LIBLTE_MME_EMM_CAUSE_NO_SUITABLE_CELLS_IN_TRACKING_AREA = b'\x0F'
LIBLTE_MME_EMM_CAUSE_MSC_TEMPORARILY_NOT_REACHABLE = b'\x10'
LIBLTE_MME_EMM_CAUSE_NETWORK_FAILURE = b'\x11'
LIBLTE_MME_EMM_CAUSE_CS_DOMAIN_NOT_AVAILABLE = b'\x12'
LIBLTE_MME_EMM_CAUSE_ESM_FAILURE = b'\x13'
LIBLTE_MME_EMM_CAUSE_MAC_FAILURE = b'\x14'
LIBLTE_MME_EMM_CAUSE_SYNCH_FAILURE = b'\x15'
LIBLTE_MME_EMM_CAUSE_CONGESTION = b'\x16'
LIBLTE_MME_EMM_CAUSE_UE_SECURITY_CAPABILITIES_MISMATCH = b'\x17' #  switch to 2G
LIBLTE_MME_EMM_CAUSE_SECURITY_MODE_REJECTED_UNSPECIFIED = b'\x18'
LIBLTE_MME_EMM_CAUSE_NOT_AUTHORIZED_FOR_THIS_CSG = b'\x19'
LIBLTE_MME_EMM_CAUSE_NON_EPS_AUTHENTICATION_UNACCEPTABLE = b'\x1A'
LIBLTE_MME_EMM_CAUSE_REQUESTED_SERVICE_OPTION_NOT_AUTHORIZED = b'\x23'
LIBLTE_MME_EMM_CAUSE_CS_SERVICE_TEMPORARILY_NOT_AVAILABLE = b'\x27' #  switch to 2G
LIBLTE_MME_EMM_CAUSE_NO_EPS_BEARER_CONTEXT_ACTIVATED = b'\x28'
LIBLTE_MME_EMM_CAUSE_SEMANTICALLY_INCORRECT_MESSAGE = b'\x5F'
LIBLTE_MME_EMM_CAUSE_INVALID_MANDATORY_INFORMATION = b'\x60'
LIBLTE_MME_EMM_CAUSE_MESSAGE_TYPE_NON_EXISTENT_OR_NOT_IMPLEMENTED = b'\x61'
LIBLTE_MME_EMM_CAUSE_MESSAGE_TYPE_NOT_COMPATIBLE_WITH_THE_PROTOCOL_STATE = b'\x62'
LIBLTE_MME_EMM_CAUSE_INFORMATION_ELEMENT_NON_EXISTENT_OR_NOT_IMPLEMENTED = b'\x63'
LIBLTE_MME_EMM_CAUSE_CONDITIONAL_IE_ERROR = b'\x64'
LIBLTE_MME_EMM_CAUSE_MESSAGE_NOT_COMPATIBLE_WITH_THE_PROTOCOL_STATE = b'\x65'
LIBLTE_MME_EMM_CAUSE_PROTOCOL_ERROR_UNSPECIFIED = b'\x6F'


DOS = LIBLTE_MME_EMM_CAUSE_EPS_SERVICES_AND_NON_EPS_SERVICES_NOT_ALLOWED
DOWNGRADE = LIBLTE_MME_EMM_CAUSE_UE_SECURITY_CAPABILITIES_MISMATCH
RELEASE = LIBLTE_MME_EMM_CAUSE_NO_SUITABLE_CELLS_IN_TRACKING_AREA